Cuprate/cuprate

- .github/workflows/ci.yml
This also removes mac and windows, they can be added back later.
> fix CI: Install dependencies

- Cargo.toml
This adds build profiles and all common dependencies to the workspace so that crates can share.
There are some crates below commented out that could be used in the future, and some ones (by me) that aren't ready but could be used one day :)
This doesn't touch any of the current dependencies of the workspace crates (yet).
> Update workspace `Cargo.toml`

- database/Cargo.toml
- database/src/config.rs
- database/src/constants.rs
- database/src/lib.rs
https://github.com/Cuprate/cuprate/pull/68 <- Previous Next -> https://github.com/Cuprate/cuprate/pull/79
Documents and fixes/adds some things to `cuprate_database::config`.
> database: docs & small fixes for `Config`

- consensus/rules/Cargo.toml
- deny.toml
- net/fixed-bytes/Cargo.toml
- pruning/Cargo.toml
- test-utils/Cargo.toml
I regenerated the file so we don't get depreciated warnings, I think I kept most options the same.
@hinto-janai
> CI: fix deny

- .github/workflows/ci.yml
- cryptonight/build.rs
- test-utils/src/monerod/download.rs
Fixes https://github.com/Cuprate/cuprate/actions/runs/8837940450/job/24268522093.
> ci: fix windows/macos

- Cargo.lock
- database/Cargo.toml
- database/src/backend/heed/env.rs
- database/src/backend/heed/error.rs
- database/src/backend/redb/env.rs
- heed: `0.20.0-alpha.9` -> `0.20.0`
- redb: `2.0.0` -> `2.1.0`
> database: update backends

- Cargo.lock
- consensus/rules/src/batch_verifier.rs
- consensus/rules/src/lib.rs
- consensus/rules/src/transactions.rs
- consensus/rules/src/transactions/ring_ct.rs
- consensus/src/batch_verifier.rs
- consensus/src/transactions.rs
This issue was already documented in the batch verifier but I didn't realize it was going to be so common, me and @SyntheticBird45 have both hit this panic.
> Consensus: fix panic in batch verifier

- Cargo.lock
- consensus/src/block.rs
This significantly speeds up performance compared to just prepping all blocks individually.
> Consensus: block batch prepper

- README.md
- SECURITY.md
Re-writes `README.md` and `SECURITY.md`, other examples:
- https://github.com/monero-project/monero
- https://github.com/paradigmxyz/reth
- https://github.com/ZcashFoundation/zebra
Rendered preview: https://github.com/hinto-janai/cuprate/tree/readme
> docs: update `README.md` & `SECURITY.md`

- storage/blockchain/README.md
- storage/blockchain/src/config/reader_threads.rs
- storage/blockchain/src/free.rs
- storage/blockchain/src/ops/block.rs
- storage/blockchain/src/ops/mod.rs
- storage/database/README.md
- storage/database/src/config/config.rs
- storage/database/src/config/sync_mode.rs
- storage/database/src/env.rs
- storage/database/src/error.rs
- storage/database/src/storable.rs
- storage/database/src/table.rs
- storage/database/src/tables.rs
- storage/database/src/transaction.rs
Cleans up and fixes some `cuprate-database` & `cuprate-blockchain` crate documentation.
> storage: doc fixes

- .github/workflows/architecture-book.yml
- .github/workflows/monero-book.yml
- .github/workflows/user-book.yml
Adds CI that builds `/books` with `mdbook` if they were modified.
> ci: add book build tests

- .github/workflows/architecture-book.yml
- .github/workflows/audit.yml
- .github/workflows/deny.yml
- .github/workflows/monero-book.yml
- .github/workflows/user-book.yml
Fixes book CI... probably (looks like they were activated in this PR):
- https://github.com/Cuprate/cuprate/actions/runs/10311760411/job/28545890153
- https://github.com/Cuprate/cuprate/actions/runs/10311760407/job/28545890147
- https://github.com/Cuprate/cuprate/actions/runs/10311760404/job/28545890160
> ci: fix book CI

- misc/ENVIRONMENT-ADVICE.md
Zed editor information is outdated. It is now available and stable on Linux and MacOS (Windows still have instabilities)
People will suffer on VSCode, RustRover and Zed are the only solution
> Update Zed in ENVIRONMENT-ADVICE.md

- helper/src/cast.rs
- helper/src/map.rs
Fixes https://github.com/Cuprate/cuprate/actions/runs/10670964743/job/29577774478.
> helper: fix clippy

- consensus/src/transactions.rs
- consensus/src/transactions/free.rs
Fixes a couple functions in the consensus code that came up during a sync
> consensus: misc fixes

- pruning/Cargo.toml
- pruning/src/lib.rs
Enables and fixes workspace lints for `cuprate-pruning`.
> pruning: enable workspace lints

- Cargo.lock
- test-utils/Cargo.toml
- test-utils/src/data/statics.rs
- test-utils/src/monerod.rs
- test-utils/src/rpc/client.rs
- test-utils/src/rpc/data/macros.rs
- test-utils/src/rpc/data/other.rs
- test-utils/src/test_netzone.rs
Enables and fixes workspace lints for `cuprate-test-utils`.
> test-utils: enable workspace lints

- net/wire/Cargo.toml
- net/wire/src/network_address.rs
- net/wire/src/network_address/epee_builder.rs
- net/wire/src/p2p.rs
- net/wire/src/p2p/admin.rs
- net/wire/src/p2p/common.rs
- net/wire/src/p2p/protocol.rs
Enables and fixes workspace lints for `cuprate-wire`.
> wire: enable workspace lints

- p2p/dandelion-tower/Cargo.toml
- p2p/dandelion-tower/src/config.rs
- p2p/dandelion-tower/src/lib.rs
- p2p/dandelion-tower/src/pool/incoming_tx.rs
- p2p/dandelion-tower/src/pool/manager.rs
- p2p/dandelion-tower/src/router.rs
- p2p/dandelion-tower/src/tests/mod.rs
- p2p/dandelion-tower/src/tests/pool.rs
Enables and fixes workspace lints for `cuprate-dandelion-tower`.
> p2p/dandelion-tower: enable workspace lints

- p2p/p2p-core/src/client/timeout_monitor.rs
Changes the timeout task to hold a weak handle now so the connection task will actually close when the `Client` is dropped
> P2P: fix connection disconnect on `Client` drop

- Cargo.toml
Move some comma positions in the workspace `Cargo.toml`
My syntax highlighter does not like `x   ,y`
> Cargo.toml: move commas

- net/levin/src/message.rs
Fix #381 
The code is wrong according to comment.
`pub fn make_fragmented_messages` of `cuprate-main/net/levin/src/message.rs`.
Modify wrong code.
> Modify wrong code

- books/user/src/SUMMARY.md
- books/user/src/getting-started/download.md
- books/user/src/introduction.md
Fixes some errors from https://github.com/Cuprate/cuprate/pull/165 review.
Also @Boog900 did you see this?: https://github.com/Cuprate/cuprate/pull/165#discussion_r1988030863
> books: user book fixes

- Cargo.lock
- binaries/cuprated/Cargo.toml
- binaries/cuprated/src/blockchain/manager.rs
- binaries/cuprated/src/blockchain/manager/handler.rs
- binaries/cuprated/src/blockchain/manager/tests.rs
- binaries/cuprated/src/txpool.rs
- consensus/context/src/alt_chains.rs
- consensus/context/src/difficulty.rs
- consensus/src/block/alt_block.rs
- consensus/src/tests/context/difficulty.rs
- p2p/p2p/src/broadcast.rs
- storage/blockchain/src/ops/blockchain.rs
- storage/blockchain/src/service/read.rs
> Cuprated: Fix reorgs

- binaries/cuprated/src/main.rs
Fixes https://github.com/Cuprate/cuprate/issues/396.
> cuprated: disable STDIN if not terminal

- Cargo.lock
- storage/database/Cargo.toml
- storage/database/README.md
- storage/database/src/backend/heed/env.rs
- storage/database/src/backend/redb/env.rs
- storage/service/Cargo.toml
- storage/service/src/service/write.rs
Closes https://github.com/Cuprate/cuprate/issues/400.
> storage: replace `println` with `tracing`

- binaries/cuprated/src/blockchain/manager/handler.rs
- binaries/cuprated/src/blockchain/manager/tests.rs
- p2p/address-book/src/store.rs
- storage/blockchain/src/ops/alt_block/chain.rs
- storage/blockchain/src/service/free.rs
- storage/blockchain/src/service/tests.rs
- storage/blockchain/src/service/write.rs
- types/types/src/blockchain.rs
closes #421 
closes #405
Adds recovery for failed reorgs
> cuprated: Bad reorg recover

- misc/changelogs/cuprated/0.0.3.md
Adds #457 and #458 to the `cuprated v0.0.3` changelog.
> changelog: add #457 + #458

- Cargo.lock
- Cargo.toml
Updates `random-rx` to https://github.com/Cuprate/randomx-rs/commit/567bdcade871f2391dc67eb90d38efaa78c24003.
> randomx-rs: `ab4a0ea` -> `567bdca`

- Cargo.lock
- Cargo.toml
- binaries/cuprated/src/config.rs
- binaries/cuprated/src/config/args.rs
- binaries/cuprated/src/config/macros.rs
- binaries/cuprated/src/config/p2p.rs
- binaries/cuprated/src/config/storage.rs
> `cuprated`: Fix config flatten

- binaries/cuprated/src/config.rs
- binaries/cuprated/src/config/default.rs
- binaries/cuprated/src/config/p2p.rs
- binaries/cuprated/src/config/rpc.rs
- binaries/cuprated/src/main.rs
- binaries/cuprated/src/p2p.rs
- binaries/cuprated/src/rpc/handlers/json_rpc.rs
- binaries/cuprated/src/rpc/server.rs
- binaries/cuprated/src/tor.rs
> make ports depend on network zones

- storage/txpool/src/free.rs
Fixes the message to update the tx-pool, we were testing with a new table that isn't in the old version.
> fix tx-pool invalid version message

- binaries/cuprated/src/config/p2p.rs
- binaries/cuprated/src/config/rpc.rs
Fix config docs for https://github.com/Cuprate/cuprate/pull/533.
> cuprated: fix `DefaultOrCustom<T>` docs
