Cuprate/cuprate

misc/ENVIRONMENT-ADIVE.md

Boog and me had to deal with severe lag with rust-analyzer. It seems it isn't suited for huge workspace development and needs extra config to reduce the laginess.
This file is just a compact version of : https://github.com/paritytech/polkadot-sdk/blob/master/docs/sdk/src/reference_docs/development_environment_advice.rs

Adding development environment advices

---

cryptonight/build.rs

Silences this warning when running `cargo doc/clippy/build`.
```
warning: cryptonight-cuprate@0.1.0: c/oaes_lib.c: In function ‘oaes_get_seed’:
warning: cryptonight-cuprate@0.1.0: c/oaes_lib.c:515:9: warning: ‘ftime’ is deprecated: Use gettimeofday or clock_gettime instead [-Wdeprecated-declarations]
warning: cryptonight-cuprate@0.1.0:   515 |         ftime (&timer);
warning: cryptonight-cuprate@0.1.0:       |         ^~~~~
warning: cryptonight-cuprate@0.1.0: In file included from c/oaes_lib.c:45:
warning: cryptonight-cuprate@0.1.0: /usr/include/sys/timeb.h:29:12: note: declared here
warning: cryptonight-cuprate@0.1.0:    29 | extern int ftime (struct timeb *__timebuf)
warning: cryptonight-cuprate@0.1.0:       |            ^~~~~
```
Either `gettimeofday` or `clock_gettime` is recommended …

cryptonight: silence `ftime` deprecated warning

---

consensus/rules/src/blocks.rs
consensus/rules/src/decomposed_amount.rs
consensus/rules/src/genesis.rs
consensus/rules/src/hard_forks.rs
consensus/rules/src/lib.rs
consensus/rules/src/miner_tx.rs
consensus/rules/src/transactions.rs
consensus/rules/src/transactions/contextual_data.rs
consensus/rules/src/transactions/ring_ct.rs
consensus/rules/src/transactions/ring_signatures.rs
consensus/src/context.rs
helper/src/atomic.rs
helper/src/thread.rs

Fixes a whole bunch of `cargo doc` errors caused from links not being within `<>`.
```
warning: this URL is not a hyperlink
--> consensus/src/context.rs:186:9
|
186 | ...// https://cuprate.github.io/monero-book/consensus_rules/transactions/unlock_time.html#getting-the-current-time
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://cuprate.github.io/monero-book/consensus_rules/transactions/unlock_time.html#getting-the-current-time>`
|
= note: bare URLs are not automatically turned into clickable links
= note: `#[warn(rustdoc::bare_urls)]` on by default
```

Fix link errors in `cargo doc`

---

Cargo.lock
Cargo.toml
helper/Cargo.toml
helper/src/atomic.rs

Adds `crossbeam` to the workspace's dependencies, and replaces `helper/`'s atomic float implementation with `crossbeam::atomic::AtomicCell<float>`.
As noted in https://github.com/Cuprate/cuprate/pull/45#issuecomment-1898503471 this:
- Is lock-free
- Allows `const fn new()`
A static assertion is also added to make sure targets that don't support lock-free atomic `32/64-bit` operations fail.

helper: use `crossbeam::atomic::AtomicCell` for atomic floats

---

database/src/key.rs

https://github.com/Cuprate/cuprate/pull/35 <- Previous Next -> https://github.com/Cuprate/cuprate/pull/61
Fixes https://github.com/Cuprate/cuprate/pull/35#discussion_r1488313416.

database: use `Infallible` for non-dup secondary keys

---

Cargo.lock
p2p/monero-p2p/tests/handshake.rs
test-utils/Cargo.toml
test-utils/src/monerod.rs
test-utils/src/monerod/download.rs

This PR removes the ability for tests to share monerod's, and makes it so if a test fails the monerod spawned for that test will output its logs.

imporove Monerod spawn stability 

---

.github/workflows/audit.yml
Cargo.lock

it seems there was a breaking change in `winnow`

CI: fix audit

---

Cargo.lock
database/Cargo.toml
database/src/backend/heed/database.rs
database/src/backend/heed/env.rs
database/src/backend/redb/database.rs
database/src/backend/redb/env.rs
database/src/backend/redb/storable.rs
database/src/backend/redb/transaction.rs
database/src/backend/redb/types.rs
database/src/database.rs
database/src/env.rs

https://github.com/Cuprate/cuprate/pull/94 <- Previous
- Upgrades to `redb 2.0.0`, fixes all errors
- Removes the `'env, 'tx` lifetimes on `trait DatabaseR{o,w}` although they remain on our custom `HeedTable` types and `'tx` remains on `redb::Table` (read/write)
Lifetime removal is due to `redb` removing some lifetimes but also because we returned owned values now.

database: `redb 1.5.0` -> `redb 2.0.0`

---

.github/workflows/ci.yml
database/Cargo.toml
database/README.md
database/src/backend/redb/env.rs

https://github.com/Cuprate/cuprate/pull/96 <- Previous
- Adds a new `redb-memory` feature flag that uses the same code from `src/backend/redb`, except that it uses `redb::backend::InMemoryBackend` instead which resides completely in memory instead of on disk

database: add `redb-memory` backend

---

database/Cargo.toml
database/src/backend/heed/database.rs
database/src/backend/heed/env.rs
database/src/backend/redb/database.rs
database/src/backend/redb/env.rs
database/src/backend/tests.rs
database/src/database.rs
database/src/env.rs

https://github.com/Cuprate/cuprate/pull/95 <- Previous Next -> https://github.com/Cuprate/cuprate/pull/97
This add various functions to `trait DatabaseR{o,w}` that are supported by both backends `heed` & `redb` - more specifically, APIs that are `BTreeMap`-like are added since both are based on B-trees.
All methods were added to the current tests in `src/backend/tests.rs`.
```rust
// Read methods.
fn iter(
&self,
) -> Result<impl Iterator<Item = Result<(T::Key, T::Value), RuntimeError>> + '_, RuntimeError>;
fn keys(
&self,
) -> Result<impl Iterator<Item = Result<T::Key, RuntimeError>> + '_, RuntimeError>;  
fn values(
&self,
) -> Result<impl Iterator<Item = Result<T::Value, RuntimeError>> + '_, RuntimeError>; 
fn contains(&self, key: &T::Key) -> Result<bool, RuntimeError>;
fn len(&self) …
```

database: add more `fn` to `trait DatabaseR{o,w}`

---

database/src/backend/heed/database.rs
database/src/backend/heed/env.rs
database/src/backend/heed/transaction.rs
database/src/backend/redb/database.rs
database/src/backend/redb/env.rs
database/src/backend/tests.rs
database/src/database.rs
database/src/env.rs
database/src/lib.rs

https://github.com/Cuprate/cuprate/pull/102 <- Previous
Fixes https://github.com/Cuprate/cuprate/pull/102#discussion_r1548695610.
- Makes `EnvInner::open_db_rw()` take a `&` instead of `&mut` write transaction
- Makes `heed` compatible by using `RefCell`
- Moves iteration functions from `trait DatabaseRo` -> `trait DatabaseIter` that are no longer accessible from `trait DatabaseRw` objects

database: make `open_db_rw()` take `&TxRw`

---

.github/workflows/ci.yml

May help https://github.com/Cuprate/cuprate/actions/runs/8945390632/job/24574288677 in https://github.com/Cuprate/cuprate/pull/111.
The function causing errors in that CI fail was stabilized in 1.76, current should be 1.77.x.
I think caching `.cargo` and `.rustup` is saving old versions of Rust then causing them to be used, so this PR replaces it with https://github.com/dtolnay/rust-toolchain.

ci: use `dtolnay/rust-toolchain`

---

.github/workflows/ci.yml

Will fix issue in https://github.com/Cuprate/cuprate/pull/65, https://github.com/Cuprate/cuprate/pull/126.

ci: downgrade to `gcc 13.2` for windows

---

database/README.md
database/src/tables.rs

Expands `database/README.md` a bit more.
Closes https://github.com/Cuprate/cuprate/pull/59.

database: more README docs

---

database/src/resize.rs
helper/src/fs.rs

Defines the `OnceLock` statics within the function they are used in instead of the outside scope.

database/helper: define `static`s within functions

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/discussion.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/proposal.md
.github/ISSUE_TEMPLATE/question.md

Adds template issue forms that get auto-labeled upon creation.
Reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository.
Examples:
- https://github.com/hinto-janai/labeler-test/issues/new/choose
- https://github.com/hinto-janai/labeler-test/issues

repo: add issue templates

---

storage/cuprate-txpool/Cargo.toml
storage/database/Cargo.toml

Fixes https://github.com/Cuprate/cuprate/actions/runs/9278688444/job/25530080931 (`storage/` crates are missing a `license` field).

storage: create Cargo.toml for `{database, cuprate-txpool}`

---

.github/workflows/audit.yml
.github/workflows/ci.yml
.github/workflows/deny.yml

Fixes:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

ci: update `actions/cache` -> `v4`

---

CONTRIBUTING.md

Formalizes the naming scheme used for Cuprate's crates.

contributing: add crate naming rules

---

Cargo.lock
net/epee-encoding/Cargo.toml
net/epee-encoding/src/container_as_blob.rs
net/epee-encoding/src/value.rs

Allows implementing `epee_encoding::EpeeValue` on outside types.
Context:
```
hinto: boog900: do I have to manually create a tagged `struct` when using `epee_encoding` with an enum?
boog900: yes ... what type do you need an enum for?
hinto: https://github.com/hinto-janai/cuprate/blob/9d262719d7074a9a4cfb06b6943f79d97af3b7a2/rpc/types/src/status.rs#L59
boog900:  or you could manually implement the `EpeeObject` trait
boog900: is that used in the binary responses?
hinto: yes, it's the `status` field in almost every response
hinto: it's technically an optimization since that field could be a `String`, but most of the time the string is known
boog900: you would have to manually implement `EpeeObject` there
boog900: wait no it's not an object
hinto: it's just a string, but `EpeeValue` is sealed …
```

epee: unseal `trait EpeeValue`

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/proposal.md
.github/ISSUE_TEMPLATE/tracking_issue.md

This adds `.github/ISSUE_TEMPLATE/tracking_issue.md` and fixes some formatting in other templates.
The purpose of this is to track wider efforts that may contain multiple PRs and/or are generally spread out. These don't usually contain the why, but if they do, they are brief. These contain no implementation detail or the how, as those are for the issues/PRs that are being tracked.
For example:
- https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+label%3AC-tracking-issue
- https://github.com/rust-lang/rust/issues/123916
A big difference between this and a proposal is that tracking issues already have consensus, i.e. the thing in question is already decided on. The what/why/where is already answered, all that is left is implementation.

repo: add `Tracking Issue` issue template

---

net/epee-encoding/src/lib.rs
net/epee-encoding/src/value.rs
net/epee-encoding/src/varint.rs

- `epee_encoding::varint::{read,write}_varint()` is made public
- The duplicated inner implementations of some `EpeeValue` objects are extracted into `epee_encoding::write_{bytes,iterator}` and made public and generic
For example, a custom `EpeeValue` implementor can now do:
```rust
impl EpeeValue for CustomStr {
/* ... */
fn write<B: BufMut>(self, w: &mut B) -> Result<()> {
epee_encoding::write_bytes(self, w)
}
}
```

epee: make `{read,write}_varint` public, create `write_{bytes,container}`

---

.github/pull_request_template.md
CONTRIBUTING.md

Follow up to: https://github.com/Cuprate/cuprate/pull/182#issuecomment-2181185856
- Adds `Submitting an issue` section that describes our issue process
- Adds a `Tracking issues` section
- Adds a `Pull request title and description` section
- Adds `.github/pull_request_template.md`
- Re-formats some sections
Preview: https://github.com/hinto-janai/cuprate/blob/contrib/CONTRIBUTING.md
The text inside pull_request_template.md auto-fills the description when creating the PRs, example: https://github.com/hinto-janai/labeler-test/compare/test?expand=1.

contributing: expand issue/PR sections, re-format

---

consensus/src/block.rs
consensus/src/context.rs
consensus/src/context/rx_vms.rs
consensus/src/context/task.rs
consensus/src/lib.rs
consensus/src/tests/context/rx_vms.rs

Currently RandomX VM initialization is broken, specifically if you request to verify a batch of blocks and RX activates somewhere in the batch and the RX seed height is outside the batch, the VM wont be initialized and we will panic.
I separated RX VMs from the rest of the context service, this will also benefit fast sync as we no longer need to initialize VMs unless specifically requested.

Consensus: fix Rx VM initialization

---

p2p/dandelion-tower/Cargo.toml
p2p/dandelion-tower/src/lib.rs
p2p/dandelion-tower/src/router.rs
p2p/dandelion-tower/src/tests/mod.rs

Fixes: #177 
This prevent freezing in the d++ router by changing the peer discover to a stream that returns an enum with a variant to tell the router there are no more outbound peers.

P2P: Fix freeze in D++

---

p2p/p2p/src/block_downloader/tests.rs

Fixes the fail here: https://github.com/Cuprate/cuprate/actions/runs/9732240689/job/26857645273
Changes the test to never generate a zero timelock as that gets interpreted as `None` instead of `Block` e deserialized.

P2P: fix block downloader test 

---

Cargo.lock
p2p/p2p/src/block_downloader.rs
p2p/p2p/src/block_downloader/request_chain.rs
p2p/p2p/src/block_downloader/tests.rs
storage/blockchain/Cargo.toml
storage/blockchain/src/service/free.rs
storage/blockchain/src/service/read.rs
types/src/blockchain.rs

Adds the DB requests and handlers for blockchain history, this history is sent to peers so they can send us their chain to sync from.
Uses the same technique as monerod, choosing the first 11 blocks from the top of the chain and then power of 2 offsets from there.

Storage: add blockchain history requests

---

.github/workflows/doc.yml
CONTRIBUTING.md
README.md

Uploads `cargo doc` to this repo's GitHub pages.
This allows pre-built, public viewing of Cuprate crate documentation on `main`, example:
- https://github.com/hinto-janai/docs
- https://hinto-janai.github.io/docs
- https://hinto-janai.github.io/docs/cuprate_blockchain/index.html
We can disable the dependencies showing but this unfortunately disables links, e.g.:
```
[`tower::Service`]
```
no longer links. Showing the list of dependencies is not bad either IMO. It makes the list bigger but all of our crates start with `cuprate_` so they are easy to spot. 
This is in this repo unlike our books because code will be updated frequently. It would be painful to manually deploy changes.
- https://github.com/paradigmxyz/reth/blob/d1efe2b19b3c69b5c534d0afaa5fe3eaf7d53a92/.github/workflows/book.yml …

ci: add `doc.yml`

---

.github/workflows/doc.yml
Cargo.lock
storage/blockchain/Cargo.toml
types/src/blockchain.rs

- Removes non-existent feature usage from `cuprate-types`
- Restore optional `serde` feature in `cuprate-blockchain` (error not shown below, but shows up if `cargo doc` is ran manually)
Fixes https://github.com/Cuprate/cuprate/actions/runs/9785148434/job/27017556001 (probably).

ci: fix `doc.yml`

---

storage/blockchain/src/free.rs
storage/blockchain/src/open_tables.rs
storage/database/Cargo.toml
storage/database/src/backend/heed/env.rs
storage/database/src/backend/redb/env.rs
storage/database/src/env.rs

The `EnvInner` and tx lifetime relation was not correct, while these types are concrete rust can infer some things that it can't if these types are kept generic, which is why this hasn't been a problem.

Storage: fix lifetimes

---

storage/database/src/backend/redb/env.rs
storage/database/src/config/sync_mode.rs

Closes https://github.com/Cuprate/cuprate/issues/149.
Worth noting this is more of a workaround than a true fix.
This maps `cuprate_database::config::SyncMode::Fast` to `redb::Durability::Eventual` instead of `redb::Durability::None` to prevent the unfreed pages issue.
This means that `redb` will differ slightly compared to `heed`, as it will sync to disk _sometime_ after a write compared to `heed` leaving it up to the OS. This is now documented on the type.

database: workaround `redb` page freeing issue

---

Cargo.lock
net/fixed-bytes/Cargo.toml
net/fixed-bytes/README.md
net/fixed-bytes/src/lib.rs

Adds a `serde` feature flag (enabled by default) to `cuprate-fixed-bytes` and documents it.
For https://github.com/Cuprate/cuprate/pull/220#discussion_r1672904392.

fixed-bytes: add `serde`, document feature flags

---

Cargo.lock
consensus/Cargo.toml
consensus/fast-sync/src/create.rs
consensus/rules/src/blocks.rs
consensus/rules/src/hard_forks.rs
consensus/src/block.rs
consensus/src/block/alt_block.rs
consensus/src/block/batch_prepare.rs
consensus/src/block/free.rs
consensus/src/context.rs
consensus/src/context/alt_chains.rs
consensus/src/context/difficulty.rs
consensus/src/context/hardforks.rs
consensus/src/context/rx_vms.rs
consensus/src/context/task.rs
consensus/src/context/weight.rs
consensus/src/tests/context/difficulty.rs
consensus/src/tests/context/hardforks.rs
consensus/src/tests/context/weight.rs
consensus/src/tests/mock_db.rs
helper/src/num.rs
helper/src/num/rolling_median.rs
storage/blockchain/src/service/mod.rs
storage/blockchain/src/service/read.rs
storage/blockchain/src/service/tests.rs
types/src/blockchain.rs
types/src/lib.rs
types/src/types.rs

Adds alt-chain handling to our consensus code.
part of: #194
Handling of alt blocks/chains is delicate balance, we need to check alt block weight however the amount of data needed to check block weight is too much to do for any alt block.
So handling of alt blocks is done in steps.
Going roughly, first we build the difficulty cache and check the blocks PoW. Then if that is valid we build the weight cache and check block weight. This means we need to add multiple new request to the context cache.
Also to prevent needing to build the caches multiple times we keep the alt caches cached in the context cache.
Some changes had to be made to the database requests/response types.

Consensus: add alt-chain handling

---

books/protocol/src/p2p_network/levin/admin.md

I forgot to change this when copy pasting

books: fix typo

---

rpc/types/README.md
rpc/types/src/bin.rs
rpc/types/src/json.rs
rpc/types/src/lib.rs
rpc/types/src/macros.rs
rpc/types/src/other.rs
rpc/types/src/rpc_call.rs

This adds some types/traits to `cuprate_rpc_types`.
This adds 6 enums for encapsulating RPC requests/responses:
- `crate::json::JsonRpcRequest` & `crate::json::JsonRpcResponse`
- `crate::bin::BinRequest` & `crate::bin::BinResponse`
- `crate::other::OtherRequest` & `crate::other::OtherResponse`
2 traits that contains some metadata about RPC request/responses:
- `RpcCall`
- `RpcCallValue`
and changes to the type generator macro to auto implement the traits.
Both enum types and metadata is needed for actual RPC usage: https://github.com/Cuprate/cuprate/pull/233.
See below review.

rpc-types: add traits and `enum` requests/responses

---

books/protocol/src/consensus_rules.md

Fixes the formatting of `PoW Hash` and updates the definition of `Block Hash` after some discussions in -site

books: change some definitions

---

net/epee-encoding/src/container_as_blob.rs
net/epee-encoding/src/io.rs
storage/blockchain/src/types.rs
storage/database/README.md
storage/database/src/storable.rs

Replace `std::mem::{size,align}_of` with `{size,align}_of` throughout the codebase.
Added to the prelude and stabilized in https://github.com/rust-lang/rust/pull/123168 (1.80).

`std::mem::{size,align}_of` -> `{size,align}_of`

---

Cargo.lock
consensus/rules/Cargo.toml
consensus/rules/src/transactions/tests.rs
consensus/src/block/alt_block.rs
consensus/src/context/task.rs
helper/Cargo.toml
helper/src/cast.rs
helper/src/lib.rs
helper/src/map.rs
net/epee-encoding/Cargo.toml
net/epee-encoding/src/lib.rs
net/epee-encoding/src/value.rs
net/levin/Cargo.toml
net/levin/src/codec.rs
net/levin/src/lib.rs
net/levin/src/message.rs
net/levin/tests/fragmented_message.rs
net/wire/Cargo.toml
net/wire/src/p2p.rs
storage/blockchain/Cargo.toml
storage/blockchain/src/ops/block.rs

Adds a `cuprate_helper::cast` module and uses it throughout the codebase.
Closes https://github.com/Cuprate/cuprate/issues/167.

helper: add and use `cast` module

---

Cargo.toml
clippy.toml
consensus/src/block/alt_block.rs
consensus/src/block/batch_prepare.rs
consensus/src/context.rs
consensus/src/context/alt_chains.rs
consensus/src/context/rx_vms.rs
consensus/src/context/task.rs
consensus/src/tests/context/rx_vms.rs
net/epee-encoding/tests/duplicate_key.rs

Adds:
- https://rust-lang.github.io/rust-clippy/master/index.html#/upper_case_acronyms
- https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#non-camel-case-types
to enforce the [Rust naming convention](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case).
---
Changes `RandomXVM` -> `RandomXVm` and some other things. To be fair `RandomX` is an uncommon case but here are some other VM examples:
- https://reth.rs/docs/reth/revm/struct.Evm.html
- https://reth.rs/docs/reth/core/rpc/types/trace/parity/struct.VmTrace.html

workspace: add naming convention lints

---

p2p/p2p/src/constants.rs
p2p/p2p/src/inbound_server.rs

Closes: https://github.com/Cuprate/cuprate/issues/176
This PR implements the following changes:
- If the maximum inbound connection semaphore reach its limit, inbound_server fn will open a tokio task to check if the node wanted to ping us. If it is the case we respond, otherwise drop the connection.
- Added some documentation to the inbound_server fn.

P2P: Implement incoming ping request handling over maximum inbound limit

---

storage/blockchain/src/ops/block.rs

This amount overflows due to tail emission, the consensus cache already does this.

Storage: use `saturating_add` for `cumulative_generated_coins`

---

net/fixed-bytes/Cargo.toml
net/fixed-bytes/src/lib.rs

Enables and fixes workspace lints for `cuprate-fixed-bytes`.

fixed-bytes: enable workspace lints

---

Cargo.lock
p2p/address-book/Cargo.toml
p2p/address-book/src/book.rs
p2p/address-book/src/book/tests.rs
p2p/address-book/src/peer_list.rs
p2p/address-book/src/peer_list/tests.rs
p2p/address-book/src/store.rs

Enables and fixes workspace lints for `cuprate-address-book`.

p2p/address-book: enable workspace lints

---

p2p/address-book/src/book/tests.rs
p2p/address-book/src/peer_list/tests.rs
p2p/address-book/src/store.rs
p2p/p2p-core/src/lib.rs
p2p/p2p-core/src/network_zones/clear.rs
p2p/p2p-core/tests/fragmented_handshake.rs
p2p/p2p-core/tests/handshake.rs
p2p/p2p/src/broadcast.rs
p2p/p2p/src/config.rs
p2p/p2p/src/connection_maintainer.rs
test-utils/src/test_netzone.rs

Moves the seed nodes to the config + removes a few unused constants 
Seeds nodes depend on the network.

P2P: move seed nodes to config

---

rpc/types/src/json.rs
test-utils/src/rpc/data/json.rs

Fixes the `HardForkInfoRequest` type, it was missing a field: https://github.com/monero-project/monero/blob/9866a0e9021e2422d8055731a586083eb5e2be67/src/rpc/core_rpc_server_commands_defs.h#L1962.

rpc-types: fix `HardForkInfoRequest`

---

Cargo.lock
Cargo.toml
types/Cargo.toml
types/src/hard_fork.rs

Adds docs, tests, `fn` to the `cuprate_types::HardFork` type.
Added changes used in #308.

types: `HardFork` improvements

---

Cargo.lock
Cargo.toml
books/architecture/src/appendix/crates.md
p2p/bucket/Cargo.toml
p2p/bucket/src/lib.rs

See: https://github.com/Cuprate/cuprate/issues/178
This PR implements a "Bucket" data structure that is a collection of data that discriminates its items into "buckets" (vector of size N) following a defined function.
- Implements Bucket data structure and Bucketable trait
- Implements Bucketable for Ipv4Addr
- Added the crate to the workspace dependencies
- Added `arrayvec` as a dependency
The end goal is to use this structure to store diverse IPs of different /16 subnets.

p2p: Implement P2P Bucket data structure

---

types/src/block_complete_entry.rs

I misnamed this field: https://github.com/monero-project/monero/blob/893916ad091a92e765ce3241b94e706ad012b62a/src/cryptonote_protocol/cryptonote_protocol_defs.h#L123

types: fix pruned `BlockCompleteEntry`

---

rpc/types/src/bin.rs
rpc/types/src/misc/misc.rs
rpc/types/src/misc/mod.rs
rpc/types/src/misc/pool_info.rs
rpc/types/src/misc/tx_entry.rs

Fixes the epee deserialization issues in https://github.com/Cuprate/cuprate/pull/334#issuecomment-2453329641 for `cuprate_rpc_types::bin::GetBlocksResponse`. Also changes some misc things.

rpc/types: fix epee deserialization for `GetBlocksResponse`

---

rpc/types/src/bin.rs

These fields were missing defaults: https://github.com/monero-project/monero/blob/893916ad091a92e765ce3241b94e706ad012b62a/src/rpc/core_rpc_server_commands_defs.h#L265-L266
reported by @spirobel

rpc/types: add missing defaults to fields

---

.github/workflows/ci.yml
Cargo.toml
clippy.toml
constants/build.rs
rpc/json-rpc/src/version.rs
storage/database/src/config/config.rs

Adds/fixes lints from [Rust 1.84](https://blog.rust-lang.org/2025/01/09/Rust-1.84.0.html) and updates the Cargo resolver to [version 3](https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions).
Added clippy lints:
- [unnecessary_map_or](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or)
- [map_all_any_identity](https://rust-lang.github.io/rust-clippy/master/index.html#map_all_any_identity)
- [unnecessary_literal_bound](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_literal_bound)

workspace: Rust 1.84

---

.github/workflows/deny.yml
.github/workflows/doc.yml

- Uses Rust stable for `cargo deny`
- Removes the boost install for `cargo doc` uploads
- `cargo deny` without explicit stable will fail when there is a new Rust stable but GitHub CI hasn't updated yet: https://github.com/Cuprate/cuprate/actions/runs/12812449148/job/35724121202
- `boost` is no longer needed

ci: stable Rust for `deny`, remove `boost` dep for docs

---

binaries/cuprated/Cuprated.toml
binaries/cuprated/src/config/storage.rs
storage/database/src/backend/heed/env.rs
storage/database/src/backend/redb/env.rs
storage/database/src/config/sync_mode.rs

- Removes `SyncMode::{Async, Threshold}`
- Sets `SyncMode::default()` to `SyncMode::Fast`
- Sets `SyncMode::FastThenSafe` to behave the same as `SyncMode::Fast` (for now, will be implemented in another PR)
Reasoning is in this meeting: https://github.com/monero-project/meta/issues/1144.

database: `SyncMode` changes

---

binaries/cuprated/src/txpool/dandelion/stem_service.rs
books/architecture/src/resources/cap/intro.md
cryptonight/src/cnaes.rs
cryptonight/src/hash_v2.rs
cryptonight/src/hash_v4.rs
cryptonight/src/slow_hash.rs
net/levin/src/lib.rs
net/wire/src/p2p.rs
net/wire/src/p2p/protocol.rs
p2p/dandelion-tower/src/config.rs
p2p/p2p-core/src/client.rs
p2p/p2p-core/src/client/connection.rs
p2p/p2p-core/src/client/handshaker.rs
p2p/p2p-core/src/client/timeout_monitor.rs
p2p/p2p-core/src/client/weak.rs
p2p/p2p-core/src/constants.rs
p2p/p2p-core/src/handles.rs
p2p/p2p-core/src/protocol.rs
p2p/p2p-core/src/protocol/try_from.rs
p2p/p2p-core/tests/handles.rs
p2p/p2p/src/broadcast.rs
storage/blockchain/src/ops/macros.rs
storage/database/src/env.rs

Fixes #383
Added a timeout for handling request to Cuprate and also add a new `Client` type that doesn't require requests be handled one at a time but only supports certain messages

P2P: fix deadlock

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml

Certain dependency installs can be removed thanks to https://github.com/Cuprate/cuprate/pull/271.
This also pins OSs to specific versions.

ci: remove dependency installs, set OS versions

---

README.md

Splits `Documentation` into a `Books` and `Crates` section (links to [`crates.md`](https://architecture.cuprate.org/appendix/crates.html)) in the readme.

readme: `Documentation` -> `Books` & `Crates`

---

clippy.toml
consensus/context/src/lib.rs
consensus/context/src/rx_vms.rs
consensus/rules/src/blocks.rs
consensus/src/block.rs

Adds exceptions to `doc-valid-idents` for clippy.
See `Configuration` in https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown.
To fix false positives like `RandomX`.

clippy: add `doc-valid-idents`

---

binaries/cuprated/src/killswitch.rs

Updates the `cuprated` killswitch timestamp using the following values from #374.
| `cuprated` version | Release codename | Release date | Killswitch date | Killswitch timestamp |
|--------------------|------------------|--------------|-----------------|----------------------|
| 0.0.1              | Molybdenite      | 2025-03-12   | 2025-04-16      | 1744761600
4 weeks from `2025-03-12` is `2025-04-09` + the 1 week grace period = `2025-04-16`.

cuprated: update killswitch timestamp

---

Cargo.lock
deny.toml

Fixes `cargo-deny`.
- Adds ignore for https://rustsec.org/advisories/RUSTSEC-2024-0436
- Removes https://rustsec.org/advisories/RUSTSEC-2024-0370.html (no longer in dep tree)
- Fixes https://rustsec.org/advisories/RUSTSEC-2025-0009.html by updating `ring`

ci: fix `deny`

---

binaries/cuprated/src/killswitch.rs

Updates the `cuprated` killswitch timestamp using the following values from #374.
| `cuprated` version | Release codename | Release date | Killswitch date | Killswitch timestamp |
|--------------------|------------------|--------------|-----------------|----------------------|
| 0.0.2              | Molybdenite      | 2025-04-09   | 2025-05-14      | 1747180800
Previous: https://github.com/Cuprate/cuprate/pull/391.

cuprated: update killswitch timestamp for `v0.0.2`

---

.github/workflows/release.yml

`Cuprated.toml` no longer exists which `release.yml` needed, this PR makes it `--generate-config` instead.

ci: fix `release.yml`

---

p2p/address-book/src/lib.rs
p2p/address-book/src/store.rs

address-book: fix panic when the peer list on the file system cannot be read
Writes a blank peer list to a temporary location, then attempts to clean the old location, and save the new file as the old file.
Fixes #399 
Cuprate can still panic if deleting the old file fails. That error will be logged, to allow manual cleanup and the latest peer list will already be saved to disk as a .tmp file. The user can remove the .tmp file extension if they wish to use it.

Use blank peer list if saved peer list cannot be read.

---

binaries/cuprated/src/blockchain/manager/handler.rs
binaries/cuprated/src/blockchain/manager/tests.rs

fixes: #435
Sad we couldn't get this before release but oh well.

`cuprated`: fix switching to main chain after a reorg

---

binaries/cuprated/src/txpool.rs
binaries/cuprated/src/txpool/incoming_tx.rs
binaries/cuprated/src/txpool/relay_rules.rs

Adds tx-pool relay rules to `cuprated`.

`cuprated`: relay rules

---

.github/workflows/release.yml
binaries/cuprated/cuprated.service
books/user/src/SUMMARY.md
books/user/src/deployment/intro.md
books/user/src/deployment/systemd.md

Closes https://github.com/Cuprate/cuprate/issues/433.

Add `cuprated.service`

---

binaries/cuprated/src/blockchain/manager/handler.rs

We were logging the top block hash - not the hash of the alt block

`cuprated`: fix alt block log

---

storage/blockchain/src/ops/output.rs

`/get_outs` was returning the wrong hash, it is fixed by this, including when it needs to return a miner tx hash.

storage: fix `get_txid` for pre-RCT outputs

---

binaries/cuprated/src/rpc/handlers/json_rpc.rs
binaries/cuprated/src/txpool/dandelion.rs
binaries/cuprated/src/txpool/dandelion/tx_store.rs
binaries/cuprated/src/txpool/incoming_tx.rs
binaries/cuprated/src/txpool/manager.rs

Fixes a deadlock where the txpool manager can be waiting on the dandelion manager and vice-versa

cuprated: fix deadlock

---

Cargo.toml
consensus/rules/src/blocks.rs
storage/blockchain/src/ops/alt_block/block.rs
types/fixed-bytes/src/lib.rs

Adds/fixes lints from Rust 1.88, 1.89, 1.90.
Added clippy lints:
- [ip_constant](https://rust-lang.github.io/rust-clippy/master/index.html#ip_constant)
- [doc_broken_link](https://rust-lang.github.io/rust-clippy/master/index.html#doc_broken_link)

 workspace: Rust 1.88..=1.90
